name: atmos_codepages
description: A starting point for Dart libraries or applications.
version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  atmos_lints:
    git: git@github.com:Atom735/atmos_lints.git
dependencies:
  meta: ^1.7.0
